### ISSUE TITLE
Add support to Python 2.7

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/DomainConnectDDNS-Python#2]
```
(env27) root@localhost:~/dyndnstest# domain-connect-dyndns setup test3.connect.domains
Traceback (most recent call last):
  File "/root/dyndnstest/env27/bin/domain-connect-dyndns", line 7, in <module>
    from dyndns.command_line import main
  File "/root/dyndnstest/env27/local/lib/python2.7/site-packages/dyndns/command_line.py", line 4, in <module>
    from dyndns import domain_setup
  File "/root/dyndnstest/env27/local/lib/python2.7/site-packages/dyndns/domain_setup.py", line 3, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError

```

**Comment by andreeadima** [comment]
Will be fixed when pull request #8 will be merged.
