### ISSUE TITLE
SSL Error when updating domain

### ISSUE THREAD

**Issue by DATKTV** [Domain-Connect/DomainConnectDDNS-Python#23]
When I try to setup this tool for my domain, it results in an ssl.CertificationError:

Setup: domain-connect-dyndns setup --domain cloud.datktv.de
Update: domain-connect-dyndns update --domain cloud.datktv.de
Result:
> root@haproxy:~# domain-connect-dyndns update --domain cloud.datktv.de
Read cloud.datktv.de config.
IP 89.245.71.215 found in A record
2020-03-01 21:09:21,828 ERROR [urllib3.connection] Certificate did not match expected hostname: api.ipify.org. Certificate: {'subject': ((('commonName', 'cloud.datktv.de'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', "Let's Encrypt Authority X3"),)), 'version': 3, 'serialNumber': '************', 'notBefore': 'Mar  1 20:03:38 2020 GMT', 'notAfter': 'May 30 20:03:38 2020 GMT', 'subjectAltName': (('DNS', 'cloud.datktv.de'),), 'OCSP': ('http://ocsp.int-x3.letsencrypt.org',), 'caIssuers': ('http://cert.int-x3.letsencrypt.org/',)}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 346, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 356, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'api.ipify.org' doesn't match 'cloud.datktv.de'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by SSLError(CertificateError("hostname 'api.ipify.org' doesn't match 'cloud.datktv.de'",),))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/bin/domain-connect-dyndns", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/dyndns/command_line.py", line 61, in main
    print(domain_update.main(domain, settings, ignore_previous_ip))
  File "/usr/local/lib/python3.6/dist-packages/dyndns/domain_update.py", line 47, in main
    response = requests.get("https://api.ipify.org", params={'format': 'json'})
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by SSLError(CertificateError("hostname 'api.ipify.org' doesn't match 'cloud.datktv.de'",),))

I don't know, why this tool is trying to match my own certificate onto api.ipify.org

**Comment by pawel-kow** [comment]
Hi, 
Looks like your machine is not able to get the IP from ipify.

Try `curl "https://api.ipify.org?format=json"` to see if this is a global problem or sth within python environment only.

**Comment by DATKTV** [comment]
I am so sorry and it is a bit embarrassing.

I have an pihole configured in my network and it seems api.ipify.org is somehow on its blocklist.
I don't know why but on friday it worked. Now its whitelisted and this solved the problem.

Thank you very much for this hint

**Comment by pawel-kow** [comment]
Glad I could help.
