### ISSUE TITLE
NameError: name 'NoDomainConnectRecordException' is not defined

### ISSUE THREAD

**Issue by almondl** [Domain-Connect/DomainConnectDDNS-Python#32]
raceback (most recent call last):
  File "/home/User/.local/lib/python3.8/site-packages/domainconnect/domainconnect.py", line 203, in _identify_domain_connect_api
    dns = self._resolver.query('_domainconnect.{}'.format(domain_root), 'TXT')
  File "/home/User/.local/lib/python3.8/site-packages/dns/resolver.py", line 1002, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: _domainconnect.My-Domain-Name., _domainconnect.My-Domain-Name.home.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dyndns/domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "/home/User/.local/lib/python3.8/site-packages/domainconnect/domainconnect.py", line 243, in get_domain_config
    domain_connect_api = self._identify_domain_connect_api(domain_root)
  File "/home/User/.local/lib/python3.8/site-packages/domainconnect/domainconnect.py", line 213, in _identify_domain_connect_api
    raise NoDomainConnectRecordException('Failed to resolve "{}"'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectRecordException: Failed to resolve "My-Domain-Name"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/domain-connect-dyndns", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dyndns/command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "/usr/local/lib/python3.8/dist-packages/dyndns/domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined

**Comment by pawel-kow** [comment]
Fixed with 9db1499c8cfdc97fd7dc9a971fca3a5c674be227
Will be included into next release
