### ISSUE TITLE
Trying to update subdomain gives me "No Domain Connect config found for domain"

### ISSUE THREAD

**Issue by daviddavo** [Domain-Connect/DomainConnectDDNS-Python#33]
```
Read vpn.<domain>.com config.
No A record found for vpn.<domain>.com
New IP: [redacted]
No Domain Connect config found for <domain>.com.
Could not update DNS record.
```

**Comment by pawel-kow** [comment]
Hi, 

Please check domainconnect record on the domain. 

`dig TXT _domainconnect.<domain>.com`

If missing it needs to be added by your DNS provider.

**Comment by john-2000** [comment]
Hi @pawel-kow 

apologies for jumping in this thread, I have a couple of 1und1.de / ionos domains and am currently using a CNAME to a dynamic DNS provider (noip) , ideally I would like to take that out of the loop and just connect the 1und1 domain directly to my variable IP server.

I am getting the following error 

after adding TXT record to 1und1

dns.resolver.NXDOMAIN: None of DNS query names exist: _domainconnect.MyDomainName.MyTLD., _domainconnect.MyDomainName.MyTLD.

could you tell me what records I need to have on 1und1.de to make this work, I am presuming currently that
I need 
A = aaa.bbb.ccc 
AAAA = xxxx:xxxx:xxxx:xxxx 
TXT with domainconnect but how 
???

Any help is much appreciate I find that https://www.ionos.co.uk/help/domains/configuring-your-ip-address/connecting-a-domain-to-a-network-with-a-changing-ip-using-dynamic-dns-linux/ is missing the required records on the 1und1 side.

thanks and apologies for the long query


`domain-connect-dyndns setup --domain www.MyDomainName.MyTLD
Traceback (most recent call last):
  File "/home/ME/.local/lib/python3.8/site-packages/domainconnect/domainconnect.py", line 203, in _identify_domain_connect_api
    dns = self._resolver.query('_domainconnect.{}'.format(domain_root), 'TXT')
  File "/home/ME/.local/lib/python3.8/site-packages/dns/resolver.py", line 1089, in query
    return self.resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/ME/.local/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/ME/.local/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: None of DNS query names exist: _domainconnect.MyDomainName.MyTLD., _domainconnect.MyDomainName.MyTLD.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ME/.local/lib/python3.8/site-packages/dyndns/domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "/home/ME/.local/lib/python3.8/site-packages/domainconnect/domainconnect.py", line 243, in get_domain_config
    domain_connect_api = self._identify_domain_connect_api(domain_root)
  File "/home/ME/.local/lib/python3.8/site-packages/domainconnect/domainconnect.py", line 213, in _identify_domain_connect_api
    raise NoDomainConnectRecordException('Failed to resolve "{}"'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectRecordException: Failed to resolve "MyDomainName.MyTLD"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ME/.local/bin/domain-connect-dyndns", line 8, in <module>
    sys.exit(main())
  File "/home/tv/.local/lib/python3.8/site-packages/dyndns/command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "/home/tv/.local/lib/python3.8/site-packages/dyndns/domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined
`

**Comment by pawel-kow** [comment]
Sure, please add CNAME record for host _domainconnect pointing at _domainconnect.1and1.com
