### ISSUE TITLE
Can you help me again ?

### ISSUE THREAD

**Issue by geds3169** [Domain-Connect/DomainConnectDDNS-Python#38]
Hello,
I come back to you because I thought I had solved my problem and it is not.

`
C:\Users\Administrator\Downloads>python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\program files (x86)\python38-32\lib\site-packages (20.2.3)

C:\Users\Administrator\Downloads>pip install domain-connect-dyndns
Collecting domain-connect-dyndns
  Using cached domain-connect-dyndns-0.0.8.tar.gz (7.3 kB)
Collecting validators>=0.12.6
  Using cached validators-0.18.1-py3-none-any.whl (19 kB)
Collecting requests>=2.21.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.0.0-py3-none-any.whl (208 kB)
Collecting domain-connect>=0.0.7
  Using cached domain_connect-0.0.7-py2.py3-none-any.whl (12 kB)
Collecting decorator>=3.4.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting six>=1.4.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting future>=0.18.1
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting publicsuffix>=1.1.0
  Using cached publicsuffix-1.1.1.tar.gz (66 kB)
Collecting cryptography>=2.8
  Downloading cryptography-3.1.1-cp38-cp38-win32.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.3 MB/s
Collecting publicsuffixlist>=0.6.11
  Using cached publicsuffixlist-0.7.4-py2.py3-none-any.whl (88 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.3-cp38-cp38-win32.whl (166 kB)
     |████████████████████████████████| 166 kB 2.2 MB/s
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: domain-connect-dyndns, future, publicsuffix
  Building wheel for domain-connect-dyndns (setup.py) ... done
  Created wheel for domain-connect-dyndns: filename=domain_connect_dyndns-0.0.8-py3-none-any.whl size=9800 sha256=974bfe193c5972a660777e293303b86f4d53deb983c5b67ae2b62afec6bfdb96
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\0b\a7\5f\e6031eadccb338b275cca174a9a16845bf428c8d5bb5264685
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=277144e852948c7c0b26d148b0a9aa4a151d08744f2c8106c8adfa327b6b86a9
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\8e\70\28\3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for publicsuffix (setup.py) ... done
  Created wheel for publicsuffix: filename=publicsuffix-1.1.1-py3-none-any.whl size=64136 sha256=3f02bc320452a9926d1aa21e2d63e36fa40c2c4a05eaf368c3430287e805054c
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\db\36\40\38c901aec542f38197f630f6a76c9432dbff8b469505e85ad1
Successfully built domain-connect-dyndns future publicsuffix
Installing collected packages: decorator, six, validators, certifi, idna, urllib3, chardet, requests, dnspython, future, publicsuffix, pycparser, cffi, cryptography, publicsuffixlist, domain-connect, domain-connect-dyndns
Successfully installed certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cryptography-3.1.1 decorator-4.4.2 dnspython-2.0.0 domain-connect-0.0.7 domain-connect-dyndns-0.0.8 future-0.18.2 idna-2.10 publicsuffix-1.1.1 publicsuffixlist-0.7.4 pycparser-2.20 requests-2.24.0 six-1.15.0 urllib3-1.25.10 validators-0.18.1

C:\Users\Administrator\Downloads>domain-connect-dyndns setup --domain web-connectivity.fr
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\domainconnect.py", line 245, in get_domain_config
    ret = self._get_domain_config_for_root(domain_root, domain_connect_api)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\domainconnect.py", line 271, in _get_domain_config_for_root
    raise NoDomainConnectSettingsException('No Domain Connect config found for {}.'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectSettingsException: No Domain Connect config found for web-connectivity.fr.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\domain-connect-dyndns.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined

C:\Users\Administrator\Downloads>domain-connect-dyndns setup --domain web-connectivity.fr
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\domainconnect.py", line 245, in get_domain_config
    ret = self._get_domain_config_for_root(domain_root, domain_connect_api)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\domainconnect.py", line 264, in _get_domain_config_for_root
    response = get_json(self._networkContext, url)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\network.py", line 155, in get_json
    return json.loads(get_http(context, url))
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\network.py", line 190, in get_http
    connection.request('GET', path)
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 1417, in connect
    super().connect()
  File "c:\program files (x86)\python38-32\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "c:\program files (x86)\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\domain-connect-dyndns.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined

C:\Users\Administrator\Downloads>pip install domain-connect-dyndns
Requirement already satisfied: domain-connect-dyndns in c:\program files (x86)\python38-32\lib\site-packages (0.0.8)
Requirement already satisfied: dnspython>=1.15.0 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect-dyndns) (2.0.0)
Requirement already satisfied: domain-connect>=0.0.7 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect-dyndns) (0.0.7)
Requirement already satisfied: validators>=0.12.6 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect-dyndns) (0.18.1)
Requirement already satisfied: requests>=2.21.0 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect-dyndns) (2.24.0)
Requirement already satisfied: six>=1.12.0 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect>=0.0.7->domain-connect-dyndns) (1.15.0)
Requirement already satisfied: publicsuffixlist>=0.6.11 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect>=0.0.7->domain-connect-dyndns) (0.7.4)
Requirement already satisfied: cryptography>=2.8 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect>=0.0.7->domain-connect-dyndns) (3.1.1)
Requirement already satisfied: publicsuffix>=1.1.0 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect>=0.0.7->domain-connect-dyndns) (1.1.1)
Requirement already satisfied: future>=0.18.1 in c:\program files (x86)\python38-32\lib\site-packages (from domain-connect>=0.0.7->domain-connect-dyndns) (0.18.2)
Requirement already satisfied: decorator>=3.4.0 in c:\program files (x86)\python38-32\lib\site-packages (from validators>=0.12.6->domain-connect-dyndns) (4.4.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\program files (x86)\python38-32\lib\site-packages (from requests>=2.21.0->domain-connect-dyndns) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\program files (x86)\python38-32\lib\site-packages (from requests>=2.21.0->domain-connect-dyndns) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\program files (x86)\python38-32\lib\site-packages (from requests>=2.21.0->domain-connect-dyndns) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files (x86)\python38-32\lib\site-packages (from requests>=2.21.0->domain-connect-dyndns) (2020.6.20)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\program files (x86)\python38-32\lib\site-packages (from cryptography>=2.8->domain-connect>=0.0.7->domain-connect-dyndns) (1.14.3)
Requirement already satisfied: pycparser in c:\program files (x86)\python38-32\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->domain-connect>=0.0.7->domain-connect-dyndns) (2.20)

C:\Users\Administrator\Downloads>domain-connect-dyndns setup --domain web-connectivity.fr
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\domainconnect.py", line 245, in get_domain_config
    ret = self._get_domain_config_for_root(domain_root, domain_connect_api)
  File "c:\program files (x86)\python38-32\lib\site-packages\domainconnect\domainconnect.py", line 271, in _get_domain_config_for_root
    raise NoDomainConnectSettingsException('No Domain Connect config found for {}.'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectSettingsException: No Domain Connect config found for web-connectivity.fr.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\domain-connect-dyndns.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "c:\program files (x86)\python38-32\lib\site-packages\dyndns\domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined`

here is the TXT in the IONOS config:

`

  | TXT | _domainconnect | "api.domainconnect.1and1.com"
-- | -- | -- | --

`

Is this still a problem with my DNS records or a problem with Python or your code?

It is really starting to exceed my skills.

Thank you for your help

**Comment by pawel-kow** [comment]
Hi, the TXT record looks ok, but for some reason your machine cannot access the API.
Pls try
```

**Comment by geds3169** [comment]
Try what ? :)

**Comment by pawel-kow** [comment]
ah, you're on windows so you don't have curl...

At first pls. check whether you can open this URL with your browser 
https://api.domainconnect.1and1.com/v2/web-connectivity.fr/settings

**Comment by geds3169** [comment]
yes i can open it

**Comment by geds3169** [comment]
urlSyncUX | "https://domainconnect.1and1.com/sync"
-- | --
urlAPI | "https://api.domainconnect.1and1.com"
urlAsyncUX | "https://domainconnect.1and1.com/async"
width | "800"
providerName | "1and1"
height | "750"

**Comment by geds3169** [comment]
It works now without having to modify anything, I have the code from IONOS. I admit that I do not understand what could have changed your link and where it comes from.

cordially

**Comment by pawel-kow** [comment]
Good. Thanks for letting know.
