### ISSUE TITLE
exception occurred

### ISSUE THREAD

**Issue by rmc0** [Domain-Connect/DomainConnectDDNS-Python#42]
hi 

do you have an idée of my problem ? 

thanks

```
~# pip3 install domain-connect-dyndns
~# domain-connect-dyndns setup --domain **MY_DOMAINE_NAME_**


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/domainconnect/domainconnect.py", line 209, in _identify_domain_connect_api
    dns = self._resolver.query('_domainconnect.{}'.format(domain_root), 'TXT')
  File "/usr/local/lib/python3.7/dist-packages/dns/resolver.py", line 1091, in query
    True)
  File "/usr/local/lib/python3.7/dist-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/usr/local/lib/python3.7/dist-packages/dns/resolver.py", line 585, in next_request
    responses=self.nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: _domainconnect.**MY_DOMAINE_NAME_**, _domainconnect.**MY_DOMAINE_NAME_**.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dyndns/domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "/usr/local/lib/python3.7/dist-packages/domainconnect/domainconnect.py", line 249, in get_domain_config
    domain_connect_api = self._identify_domain_connect_api(domain_root)
  File "/usr/local/lib/python3.7/dist-packages/domainconnect/domainconnect.py", line 219, in _identify_domain_connect_api
    raise NoDomainConnectRecordException('Failed to resolve "{}"'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectRecordException: Failed to resolve "**MY_DOMAINE_NAME_**"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/domain-connect-dyndns", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/dyndns/command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "/usr/local/lib/python3.7/dist-packages/dyndns/domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined


```

**Comment by pawel-kow** [comment]
Hi @rmc0,
did you query the TXT record _domainconnect.<yourdomainname> from this machine? It seems it's not resolving (missing from DNS configuration?)

**Comment by rmc0** [comment]
sorry after some search and test I don't really know how do that
thanks

**Comment by pawel-kow** [comment]
Please try with dig
There is an online one as well https://toolbox.googleapps.com/apps/dig/

Query TXT record on _domainconnect.<your.domain>

**Comment by pawel-kow** [comment]
no activity, closing.
